stages:
  - build

build:
  stage: build
  image: node
  only:
    - merge_requests
  script:
    - echo "Start building app"
    - npm install
    - npm run-script build
    - echo "Build completed"

test:
  stage: build
  image: node
  only:
    - merge_requests
  script:
    - echo "Starting test procedure"
    - npm install
    - npm run test
    - echo "Tests completed"
  