SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS VersionInfo;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Organization;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Visitor;
DROP TABLE IF EXISTS Visit;
DROP EVENT IF EXISTS cleaning;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE VersionInfo
(
    Version INTEGER NOT NULL
);

CREATE TABLE Admin
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    HashedPassword TEXT NOT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE Organization
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE Employee
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(12) NOT NULL UNIQUE,
    Email VARCHAR(50),
    PRIMARY KEY (Id)
);

CREATE TABLE Visitor
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(12) NOT NULL UNIQUE,
    OrganizationId INTEGER NOT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (OrganizationId) REFERENCES Organization(Id)
);

CREATE TABLE Visit
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    VisitorId INTEGER NOT NULL,
    EmployeeId INTEGER NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    Reference INTEGER NOT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (VisitorId) REFERENCES Visitor(Id),
    FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);

SET GLOBAL event_scheduler = ON;

CREATE EVENT cleaning ON SCHEDULE EVERY 1 MONTH ENABLE
  DO 
  DELETE FROM visit
  WHERE `StartDate` < CURRENT_TIMESTAMP - INTERVAL 3 YEAR;