SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS EventLog;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE EventLog
(
    Id INTEGER NOT NULL AUTO_INCREMENT,
    Date DATETIME NOT NULL,
    Description TEXT NOT NULL,
    PRIMARY KEY (Id)
);